[[redirects]]
  from = "http://tools.matizthinkinglab.com/*"
  to   = "https://tools.matizthinkinglab.com/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://matizthinkinglab-tools.netlify.app/*"
  to   = "https://matizthinkinglab-tools.netlify.app/:splat"
  status = 301
  force  = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
